#!/bin/bash

# This is a simple script to run iperf3 as a server
# Using the default bridge network with firewall
# Debian 12
# https://hub.docker.com/r/networkstatic/iperf3
# 2/21/2024

echo "Please provide a name for the server container, no spaces."
read SRV01

echo "The name of the server is $SRV01"
docker run -it --rm -p 5201:5201 --name="$SRV01" networkstatic/iperf3 -s

echo "End of script"
